name: privoxy Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Get current date
      uses: srfrnk/current-time@master
      id: current-date
      with:
        format: YYYYMMDD

    #- name: Build the Docker image
      #run: docker build ./privoxy --file ./privoxy/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/privoxy:$(date +%s)

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./privoxy
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/privoxy:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/privoxy:${{ steps.current-date.outputs.formattedTime }}

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/privoxy
        short-description: 'privoxy docker image based on Alphine Linux.'
        readme-filepath: ./privoxy/README.md

