name: frpc + frps Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - frpc/**
      - frps/**
      - .github/workflows/frp.yml
  pull_request:
    branches: [ master ]
    paths:
      - frpc/**
      - frps/**
      - .github/workflows/frp.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Get current date
      uses: srfrnk/current-time@master
      id: current-date
      with:
        format: YYYYMMDD

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./frpc
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/frpc:latest

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/frpc
        short-description: 'Frpc docker image.'
        readme-filepath: ./frpc/README.md

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./frps
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/frps:latest

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/frps
        short-description: 'Frps docker image.'
        readme-filepath: ./frps/README.md

