name: toolbox Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - toolbox/**
  pull_request:
    branches: [ master ]
    paths:
      - toolbox/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Get current date
      uses: srfrnk/current-time@master
      id: current-date
      with:
        format: YYYYMMDD

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    #- name: Push to Docker Hub
      #uses: docker/build-push-action@v2
      #with:
        #context: ./toolbox
        #username: ${{ secrets.DOCKERHUB_USERNAME }}
        #password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        #push: true
        #tags: |
          #${{ secrets.DOCKERHUB_USERNAME }}/toolbox:${{ steps.current-date.outputs.formattedTime }}

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/toolbox
        short-description: 'toolbox docker image based on Alpine Linux.'
        readme-filepath: ./toolbox/README.md

